title: Brian's Quest
author: Gilokk0
name: Brian's Quest
description: Brian is on a quest to find the love of his life. Will he find it? Play and find out.
show_downloads: true
markdown: kramdown

theme: jekyll-theme-merlot
